### PR TITLE
ecmaVersion 8 + object rest/spread

### PR DESCRIPTION
**Pull request by hzoo**
Can be a minor

### CODE REVIEW

**Comment by kaicataldo** [comment]
:+1:

**Comment by hzoo** [comment]
WHAT

**Comment by nemtsov** [comment]
👍

**Comment by nemtsov** [comment]
no `.travis.yml`?

**Comment by hzoo** [comment]
Yeah someone turned it on but I checked the box to not run if no travis.yml for next time

**Pull request merged**
